// Generated by CoffeeScript 1.3.1
(function() {
  var Cheque;

  Cheque = (function() {

    Cheque.name = 'Cheque';

    function Cheque() {}

    return Cheque;

  })();

  Cheque.getListFromServer = function() {
    return $.get("/payment/getCheques", function(results) {
      var cheque, total, _i, _len, count, count_unique;
      var ch_bank = "-1";
      var ch_agency = "-1";
      var ch_account = "-1";
      var ch_number = "-1";
      var color_back = "";
      var color = "";
      var title = "";

      $("#grid tbody").html("");
      eval("results = " + results);
      total = 0.0;
      count = 0;
      count_unique = 0;
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        cheque = results[_i];
        total += cheque.value;
        count += 1;
        if (ch_bank != cheque.bank || 
          ch_agency != cheque.agency || 
          ch_account != cheque.account || 
          ch_number != cheque.number) {
          count_unique += 1;
          ch_bank = cheque.bank
          ch_agency = cheque.agency
          ch_account = cheque.account
          ch_number = cheque.number
          color_back = "";
          title = ""
        } else {
          color_back = "red"
          title = "Cheque duplicado: banco, agencia, conta e número"
        }
        cheque.date = getDateBr(new Date(cheque.date));
        cheque.gooddate = getDateBr(new Date(cheque.gooddate));
        var color = "";
        if (cheque.date != cheque.gooddate) {
          color = "red"
        } else {
          color = ""
        }
        var obsColor = "";
        if (cheque.obs.indexOf('Revertido') != -1) {
          obsColor = "red"
        } else {
          obsColor = ""
        }
        $("#grid tbody").append("<tr>" +
          "<td>" + cheque.id + "</td>" +
          "<td title='" + title + "' style='background-color:" + color_back + "'>" +
            "<img width='24px' src='" + cheque.bankLogo + "' title='" + cheque.bank + " " + cheque.bankName + "'/>" + "</td>" + 
          "<td title='" + title + "' style='background-color:" + color_back + "'>" + cheque.agency + "</td>" +
          "<td title='" + title + "' style='background-color:" + color_back + "'>" + cheque.account + "</td>" + 
          "<td title='" + title + "' style='background-color:" + color_back + "'>" + cheque.number + "</td>" + 
          "<td>" + (cheque.value.formatMoney()) + "</td>" +
          "<td>" + cheque.date + "</td>" + 
          "<td style='color:" + color + "'>" + cheque.gooddate + "</td>" + 
          "<td>" + "<a style='line-height: 105%' href='/customer/edit?id="+cheque.customerId+"' target='_customer_maste'>"+cheque.customer+"</a>"+ "</td>" +
          "<td style='color:" + obsColor + "'>" + cheque.obs + "</td>" +
// rigel 19/06/2018
// comentei pq marcava o chque sem marcar o lancto financeiro
// e nem alterava saldo e conta
//          "<td><a href='#' class='_popover danger marker' rel='popover' data-content='Marcar como recebido!'  data-original-title='Recebido?' data-id='" + cheque.id + "' data-confirm-message='que deseja marcar o cheque como descontado'><img src='/images/good.png'></a></td>" +
          "</td><td><a title='" + cheque.auditstr + "' href='#' ><img width='24px' src='/images/audit.png'/></a></td>" +
          "</tr>");
/*        
        $(".marker").click(function() {
          return $.get("/payment/cheque/makeAsReceived/" + $(this).attr("data-id"), function() {
            alert("Marcado com sucesso!");
            return Cheque.getListFromServer();
          });
        });
*/      
      }
      $("#count").val(count);
      $("#count_unique").val(count_unique);
      return $("#total").val(total.formatMoney());
    });
  };

  $(function() {
    $("#send").click(function() {
      return Cheque.getListFromServer();
    });
    return Cheque.getListFromServer();
  });

}).call(this);
